#! /bin/sh
#
# to_mp3
#
# Converts the specified audio files to equivalent MP3 files


for file in "$@"
do
  mp3_file="${file%.*}.mp3"
  nice -n 18 avconv -i "$file" "$mp3_file" \
      && touch -r "$file" "$mp3_file" \
      && rm "$file"
done
